### ISSUE TITLE
[BUG] Descriptions and examples of the logged data are not available 

### ISSUE THREAD

**Issue by piahalkour** [rwth-acis/mobsos-evaluation-center#121]
In the Dev network the descriptions and examples of the logged data are not available. Just shows "The service has no message descriptors available. Please contact the service developers. "

**To Reproduce**
1. Go to MobSOS Evaluation Center in the Dev-network and choose the application "mensa"
2. Click on "edit" of any factor, click on "Data source"
3. Try to open the message descripitons

**Screenshots**
![grafik](https://user-images.githubusercontent.com/56801151/169242669-7011625d-12ae-41db-899b-3817b7afa9fe.png)

**Comment by lakhoune** [comment]
For me this issue does not occur. Are you using the latest version? Maybe try to delete the cache and refresh the page

**Comment by piahalkour** [comment]
Works after deleting cache!
