### ISSUE TITLE
screenshots of the evaluation center

### ISSUE THREAD

**Issue by klamma** [rwth-acis/mobsos-evaluation-center#6]
Would it be possible to get some screenshots of the evaluation center with meaningful content.

**Comment by lakhoune** [comment]
Here are some screenshots. I will be adding more once [this issue](https://github.com/rwth-acis/las2peer/issues/93) is resolved. I will be adding them to the wiki then
Screenshot of the community selection:
![2021-05-24 10_53_58-Window](https://user-images.githubusercontent.com/38857665/120083640-53653300-c0ca-11eb-8334-ccc6ca1e0793.png)
Screenshot of the service selection:
![2021-05-18 15_21_48-Window](https://user-images.githubusercontent.com/38857665/120083344-57905100-c0c8-11eb-9483-5f67a3024449.png)
Screenshot for success measures of the tmitocar service success model:
![2021-05-21 22_55_53-Window](https://user-images.githubusercontent.com/38857665/120083355-6840c700-c0c8-11eb-9200-0140bb2e7f02.png)
