### ISSUE TITLE
Create a limesurvey connector

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/mobsos-evaluation-center#96]
This connector should communicate between the evaluation center and the limesurvey instance. In the evaluation center users should be able to fill in a form to set the necessary fields required for this connection (this includes the url of the limesurvey instance, as well as the necessary credentials for authentication

**Comment by lakhoune** [comment]
Might be able to use the survey handler service for this?

**Comment by lakhoune** [comment]
@Taeuber-hub do you think https://github.com/rwth-acis/Survey-Handler-Service could be used for this?

**Comment by Taeuber-hub** [comment]
Yes the service could be used for it, I will work on that

**Comment by lakhoune** [comment]
@Taeuber-hub could you provide the response like this?:
```json
[
  {
    "question": "I am:",
    "type": "L",
    "responses": {
      "Male": 23,
      "Female": 1
    }
  },
  {
    "question": "I use messaging apps daily.",
    "type": "5",
    "responses": { "1": 1, "2": 1, "4": 2, "5": 20 }
  },
  {
    "question": "I already completed moodle quizzes before.",
    "type": "L",
    "responses": { "Yes": 23, "No": 1 }
  }
]
```

**Comment by Taeuber-hub** [comment]
@lakhoune Yes I can arrange the response this way. Currently the function returns the responses the way LimeSurvey provides them, which is: 

{
   "responses":[
      {
         "1":{
            "id":"1",
            "submitdate":"2022-05-17 09:12:45",
            "titleQuestion1":"answer",
            "titleQuestion2":"answer"
         }
      },
      {
         "2":{
            "id":"2",
            "submitdate":"2022-05-24 21:26:58",
            "titleQuestion1":"answer",
            "titleQuestion2":"answer"
         }
      },
      {
         "3":{
            "id":"3",
            "submitdate":"2022-06-03 13:26:59",
            "titleQuestion1":"answer",
            "titleQuestion2":"answer"
         }
      }
   ]
}
